export const ROUTES = {
  HOME: "/",
  REGISTRATION: "/registration",
  LOGIN: "/login",
  GENDER_BY_NAME: "/gender-by-name",
  SPACE_MISSION: "/space-mission",
  PROFILE_CARD: "/profile-card",
  ABOUT: "/about",
  CONTACTS: "/contacts",
  ACCOUNT: "/account",
  ACCOUNT_SETTINGS: "/account/settings",
  USER_INFORMATION: "/account/user-information",
  PRODUCTS: "/products",
  USERS: "/users",
  PRODUCTS_ID: "/products/:id",
  USERS_ID: "/users/:id",
  NOT_FOUND: "*",
} as const;
