export const ROUTES = {
  HOME: "/",
  REGISTRATION: "/registration",
  LOGIN: "/login",
  ABOUT: "/about",
  CONTACTS: "/contacts",
  ACCOUNT: "/account",
  ACCOUNT_SETTINGS: "/account/settings",
  USER_INFORMATION: "/account/user-information",
  PRODUCTS: "/products",
  PRODUCTS_ADD: "/product/add",
  USERS: "/users",
  PRODUCTS_ID: "/products/:id",
  USERS_ID: "/users/:id",
  NOT_FOUND: "*",
} as const;
